### ISSUE TITLE
Redirect after Login doesn't work

### ISSUE THREAD

**Issue by schauerdesign** [antwerpes/ap_docchecklogin#5]
Hi,

I would like to set a redirect to a target page after successful login. I added the target page in the user's properties and also in the plugin content record. I set basic.useFeLoginRedirect to 1 in my template setup but it still doesn't redirect to the right page. It only shows the message "You are logged in as DocCheck User. Logout." on the same page. How can I redirect the user to a landing page I created after successful login?

Thanks
Stefanie

**Comment by jeongil** [comment]
Hello Sabine,

sorry for the late response.

In case you still need support: which target page for your login is configured in Doccheck Cream?

The target page has to have the DocCheck Plugin included so the redirect logic will be executed. So e.g. set the target page to the same page the login iframe is included in.

Greetings,

Jeong

**Comment by Havrin** [comment]
Hello @schauerdesign ,

I got the same issue and found a solution.
The Problem is, that in the documentation it says you should add https://your-domain.de/login?logintype=login&dc=YOUR_DC as your target url. In the Extension the value, if the user should be redirected, is stored in $GLOBALS, but is lost because a redirect has already happened before. Why? Because if you use RealURL, it checks for a missing slash by default (you can probably disable this in the real url config). So if you use this:
https://your-domain.de/login?logintype=login&dc=YOUR_DC
instead of this:
https://your-domain.de/login/?logintype=login&dc=YOUR_DC (note the slash after "login")
the stored value in $GLOBALS is lost and the redirect does not happen. So just change your target URL in doccheck CReaM to an URL with a slash at the end and everything should work :)

@jeongil you may consider changing your doc or note that as a hint below the image showing the config of doccheck CReaM.

Happy Coding,
Havrin
